[package]
name = "patina_mm_supervisor_core"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme = "README.md"
description = "A pure Rust implementation of the MM Supervisor Core for standalone MM mode environments."

# Metadata to tell docs.rs how to build the documentation when uploading
[package.metadata.docs.rs]
features = ["doc"]

# Example binary showing how to build a PE/COFF MM Supervisor
[[bin]]
name = "example_mm_supervisor"
path = "bin/example_mm_supervisor.rs"

[dependencies]
linkme = { workspace = true }
log = { workspace = true }
patina = { workspace = true }
patina_adv_logger = { workspace = true }
patina_internal_cpu = { workspace = true }
patina_mm_policy = { workspace = true }
patina_mm = { workspace = true }
patina_paging = { workspace = true }
patina_stacktrace = { workspace = true }
r-efi = { workspace = true }
spin = { workspace = true }
x86_64 = { workspace = true, features = [
    "instructions",
    "abi_x86_interrupt",
] }

[dev-dependencies]
mockall = { workspace = true }
serial_test = { workspace = true }

[features]
default = []
std = []
doc = []
