[package]
name = "patina_internal_mm_common"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme = "README.md"
description = "Shared type definitions for MM supervisor and user cores."

[lints]
workspace = true

[dependencies]
r-efi = { workspace = true }
